### ISSUE TITLE
A variable used in this view was not found. Please refer to the help for this view.

### ISSUE THREAD

**Issue by larrychenlawrence** [renesas/fsp#136]
![image](https://user-images.githubusercontent.com/8140000/137252126-98178219-4c89-4ef8-ba43-1990aa515c7e.png)

**Comment by TakashiMakita** [comment]
It looks an emulator is not connected yet, because "Communication Status: Disconnect" is displayed. Firstly, please start debugging and run (resume) your program on your target system.
 
If you still get this message, check the following points.
- The touch middleware exists in your project.
- Debug information is output.
- A main process for touch is called in the main() function.
 
Also, if you are using FSP V3.3.0 or V3.4.0, could you try following workarounds?
- Enable "Support for QE monitoring using UART" in the properties of rm_touch
