### ISSUE TITLE
The RTC may not be initialized for some devices when calling R_RTC_Open() after a power-on reset

### ISSUE THREAD

**Issue by jprofeta-rea** [renesas/fsp#169]
## Issue
On some devices, when a power-on reset occurs, the RTC will be started upon exiting reset. This behavior may cause the RTC initialization to be skipped when the R_RTC_Open() api is called.

## Workaround
Clear the RCR2.START bit before calling R_RTC_Open() if a power-on reset has occurred.

Example:
```
void hal_entry(void)
{
    /* Check to see if a power-on reset has occurred. */
    if ((R_SYSTEM->RSTSR0 & R_SYSTEM_RSTSR0_PORF_Msk) != 0U)
    {
        /* Clear the START bit and wait for the value to synchronize. */
        R_RTC->RCR2_b.START = 0U;
        FSP_HARDWARE_REGISTER_WAIT(R_RTC->RCR2_b.START, 0U);
    }

    /* application code here */

    R_RTC_Open (&g_rtc0_ctrl, &g_rtc0_cfg);

    /* application code here */
}
```

**Comment by HouseSimOn** [comment]
What is the effect of this issue? Other RTC functions return FSP_ERR_NOT_OPEN? In described workaround registers with date and time will be cleared, right?

I have had a weird problem twice (I don't know how to reproduce it). RDAYCNT counter is not being incremented and I have following case:
- 15.02.2022 23:59:58
- 15.02.2022 23:59:59
- 15.02.2022 00:00:00 (!15 instead of 16)
- 15.02.2022 00:00:01.(!15 instead of 16)

Problem dissapears when I discharge battery used for RTC purposes. Has anybody had similar problem?
RA6M5, FSP 0.3.3.
