### ISSUE TITLE
RA6E1 projects cannot add r_ether module to project

### ISSUE THREAD

**Issue by renesas-brandon-hussey** [renesas/fsp#171]
# Issue

RA6E1 MCUs do have an Ethernet peripheral but the r_ether and r_ether_phy modules will not show up as available in e2 studio projects. The image below shows the missing modules. This will be fixed in a future FSP release.

![image](https://user-images.githubusercontent.com/53097876/149018885-e0cd5557-a296-4fe5-adb8-5b2ac95070af.png)

# Workaround

The r_ether and r_ether_phy source can be added to an e2 studio project using the Components tab.

![image](https://user-images.githubusercontent.com/53097876/149019288-01530611-3dd5-4f55-803c-cff0c4f47e37.png)

This will not create the generated code to help setup the module. This will also not enable higher level stacks to be created (eg: TCP/IP stack).

**Comment by DaveCocca** [comment]
Hi Brandon,

Who found this issue?

Dave

From: Brandon Hussey ***@***.***>
Sent: Tuesday, January 18, 2022 11:11 AM
To: renesas/fsp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [renesas/fsp] RA6E1 projects cannot add r_ether module to project (Issue #171)

Issue

RA6E1 MCUs do have an Ethernet peripheral but the r_ether and r_ether_phy modules will not show up as available in e2 studio projects. The image below shows the missing modules. This will be fixed in a future FSP release.

[image]<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F53097876%2F149018885-e0cd5557-a296-4fe5-adb8-5b2ac95070af.png&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OhZdES2eY1azRVsylTeFbA2HtJm7YMd951qZOiEYwqc%3D&reserved=0>

Workaround

The r_ether and r_ether_phy source can be added to an e2 studio project using the Components tab.

[image]<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F53097876%2F149019288-01530611-3dd5-4f55-803c-cff0c4f47e37.png&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GhA2odbTWCnptoie6amB6%2BZgsas9mzm5vLMj6R8FahQ%3D&reserved=0>

This will not create the generated code to help setup the module. This will also not enable higher level stacks to be created (eg: TCP/IP stack).

-
Reply to this email directly, view it on GitHub<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenesas%2Ffsp%2Fissues%2F171&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=toDUYT4os7AcB%2B%2BLCbO9HvnrWGYG1ZAAJHeTIEyShyk%3D&reserved=0>, or unsubscribe<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANBGLWHWNSMOFV6ZJTHPCBDUWWGJXANCNFSM5MHSTORA&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4tUb6MufY8BxCamOZ4ef1Qver4X%2Br4UICGOCaLCjTOY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MQdPbALXkDGgeU353asqNIABSjLikj9e2sr%2BVyFbisI%3D&reserved=0> or Android<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdavid.cocca%40renesas.com%7Cfb0db416fc49410c31ee08d9da9d23e2%7C53d82571da1947e49cb4625a166a4a2a%7C0%7C0%7C637781190710012863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mw6sUMJyZz8rAvk3zij3pzuH622pBSmzc3DooFaQaGo%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>



Disclaimer: This message and any files or text attached to it are intended only for the recipients named above and contain information that may be confidential or privileged. If you are not an intended recipient, you must not forward, copy, use or otherwise disclose this communication or the information contained herein. In the event you have received this message in error, please notify the sender immediately by replying to this message, and then delete all copies of it from your system. Thank you.
